### ISSUE TITLE
Remind me

### ISSUE THREAD

**Issue by Kusoneko** [TehSeph/Neko.js#4]
!remindme to [do something] in X [time unit]
or
!remindme in X [time unit] to [do something]

would reply with

@ Person, I'll remind you in X [time unit]

and then after X times ([time unit] converted to seconds)

@ Person, [do something]

**Comment by TehSeph** [comment]
Looking at this now, it just seems like it would be hell to do. What were we thinking lol?

You're more than welcome to give it a shot in [Kusoneko/Nekobot](https://github.com/Kusoneko/Nekobot) and I'll try and port it... but I'm not gonna attempt this. Natural language recognition is a *biiiiiiiitch*.

**Comment by Perpetucake** [comment]
I suggest the lazy way and just force the user to use simple splits and searches and require syntax like this !remindme "something bla bla" "5h3m26s", someone requested this for DougleyBot and once I get unlazy enough to write it over there I'll try to toss it in over here (no promises)
